version: 2
jobs: 
  build:
    docker: 
      - image: circleci/ruby:2.6.5
    steps: 
      - checkout

      - run:
          name: install bundler
          command: gem install bundler

      - run:
          name: install gems
          command: bundle install

      - run:
          name: compile
          command: rake compile

      - run:
          name: test
          command: rake test