version: 2
jobs: 
  build:
    docker: 
      - image: ruby:2.7.0-preview3
        environment:
          CC_TEST_REPORTER_ID: '1bc997946c470551ec0f384e37c5646f12d924d9ab98251809a7d6baf5154445'
    steps: 
      - checkout

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: install bundler
          command: gem install bundler

      - run:
          name: install gems
          command: bundle install

      - run:
          name: compile
          command: bundle exec rake compile

      - run:
          name: before-build
          command: ./cc-test-reporter before-build

      - run:
          name: test
          command: bundle exec rake test

      - run:
          name: after-build
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?