name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install build environment 
      run: |
        gem install bundler
        rake clean && rake compile && rake install && rake test