name: CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    branches:
    - master
  - cron: 0 0 * *
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
