name: CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-ruby@v1
      with: 
        ruby-version: '2.6'
    - name: Build & Test
      run: |
        gem install bundler
        bundle install
        rake install
        rake test